name: borrar cagada terraform
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Terraform Init
        run: terraform init
      - name: Terraform Plan
        run: terraform plan
      - name: Terraform Destroy
        run: terraform destroy -auto-approve
      - name: Mensaje de confirmación
        run: echo "Terraform destroy realizado con exito"